services:
  frontapp:
    build: ./frontapp/
    ports:
      - "8000:8080"
    environment:
    - BACK_URL=http://localhost:8081/backapp
  backapp:
    build: ./backapp/
    ports:
      - "9000:8081"
    