services:
  
  frontapp:
    build: ./frontapp/
    ports:
    - 8080:8080
    environment:
    - BACK_URL=http://localhost:8081
  
  backapp:
    build: ./backapp/
    ports:
    - 8081:8081
  
#volumes:
#  f_b: {}
    