services:
  
  frontapp:
    image: frontapp
    build: ./frontapp/
      dockerfile: ./Dockerfile
    ports:
    - 8080:8080
    environment:
    - BACK_URL=backapp
  
  backapp:
    image: backapp
    build: ./backapp/
      dockerfile: ./Dockerfile
    ports:
    - 8081:8080
    